color:
  error: 0xf08080
  success: 0x7bf1a8
  info: 0xfbf8cc

image:
  error: https://imgur.com/jLmFNU8.png
  success: https://imgur.com/9sE0qDr.png
  info: https://imgur.com/dsCFSDu.png

emote:
  error: <:error:1109467955437240371>
  success: <:success:1109467958054506536>
  info: <:info:1109467933270364241>
