version: '3.9'

services:
  kazoeru:
    build: .
    restart: unless-stopped
    environment:
      - REDIS_URI=redis://redis:6379
      - DB_BIND=postgresql+asyncpg://kazoeru:kazoeru@postgres:5432/kazoeru
    env_file:
      - .env
    volumes:
      - /etc/kazoeru/data:/bot/kazoeru/data

  postgres:
    image: postgres:13-alpine
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=kazoeru
      - POSTGRES_USER=kazoeru
      - POSTGRES_PASSWORD=kazoeru
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kazoeru"]
      interval: 2s
      timeout: 1s
      retries: 5

  redis:
    image: redis:latest
    hostname: redis
    restart: unless-stopped
    command:
      --save 60 1
    volumes:
      - redis:/data

volumes:
  redis:
