version: '3.9'

services:
  bot:
    build: .
    image: nightcafegg/kazoeru
    container_name: kazoeru-bot
    restart: unless-stopped
    environment:
      - REDIS_HOST=kazoeru-redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    
  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: kazoeru-redis
    restart: unless-stopped
    volumes:
      - /etc/redis/kazoeru:/data
    