version: '3.9'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - /etc/kazoeru/data:/bot/kazoeru/data

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    hostname: redis
    restart: unless-stopped
    volumes:
      - /etc/kazoeru/redis:/data
