name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black isort
      - name: Run Ruff
        run: ruff check --format=github .
      - name: Run Black
        run: black --check .
      - name: Run Isort
        run: isort --check-only .
